config/routes.rb
Rails.application.routes.draw do
  root 'todos#home'

  resources :todos
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/todo.rb
class Todo < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  def index
    @todos = Todo.all
  end

  def show
    @todo = Todo.find(params[:id])
  end

  def new
    @todo = Todo.new
  end

  def create
    @todo = Todo.new(todos_params)
    if @todo.save
      redirect_to todos_path
    else
      render :new
    end
  end

  def edit
    @todo = Todo.find(params[:id])
  end

  def update
    @todo = Todo.find(params[:id])

    if @todo.update(todos_params)
      redirect_to todos_path
    else
      render :edit
    end
  end

  def destroy
    Todo.find(params[:id]).destroy
    redirect_to todos_path
  end

  private

  def todos_params
    params.require(:todo).permit(:title, :description, :urgency, :completed)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/layouts/_navbar.html.erb
<%= link_to 'Home', todos_path %>
<%= link_to 'About This App', root_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TodoList</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/todos/edit.html.erb
<h1>Edit Todo</h1>

<%= render 'layouts/navbar' %>
  <%= yield %>

<hr>

<%= form_for @todo do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <br>
  <%= f.label :description %>
  <%= f.text_area :description %>
  <br>
  <%= f.label :urgency %>
  <%= f.text_field :urgency %>
  <br>
  <%= f.label :completed %>
  <%= f.check_box :completed %>
  <br>
  <%= f.submit %>
<% end %>

<%= link_to 'Back', todos_path %>

app/views/todos/home.html.erb
<br><br><br><br><br>
<hr>
<h1>To Do List App</h1>
<br>
<h3>Organize your life with a digital to-do list for the 21st century</h3>
<h4>Cutting edge tech, easy to use</h4>
<h3>Yep</h3>
<%= render 'layouts/navbar' %>
<%= yield %>
<hr>

app/views/todos/index.html.erb
<h1>Todos</h1>

<%= render 'layouts/navbar' %>
  <%= yield %>

<hr>
<p><%= link_to 'New Todo', new_todo_path %></p>

<% @todos.each do |todo| %>
  <h2><%= todo.title %></h2>
  <%= link_to 'Show Todo', todo_path(todo) %>
  <%= link_to 'Edit Todo', edit_todo_path(todo) %>
  <%= link_to 'Delete Todo', todo, method: :delete %>
<% end %>

app/views/todos/new.html.erb
<h1>New To-do Item</h1>

<%= render 'layouts/navbar' %>
  <%= yield %>

<hr>

<%= form_for @todo do |f| %>

  <%= f.label :title %>
  <%= f.text_field :title %>
  <br>

  <%= f.label :description %>
  <%= f.text_area :description %>
  <br>
  <%= f.label :urgency %>
  <%= f.text_field :urgency %>
  <br>
  <%= f.label :completed %>
  <%= f.check_box :completed %>
  <br>
  <%= f.submit %>

<% end %>

<%= link_to 'Back', todos_path %>

app/views/todos/show.html.erb
<%= render 'layouts/navbar' %>
  <%= yield %>

<hr>

<h1>
  <%= @todo.title %>
</h1>

<h4>
  Description:
  <br>
  <%= @todo.description %>
</h4>

<h4>
  Urgency:
  <br>
  <%= @todo.urgency %>
</h4>

<p><i>Complete?</i></p>

<h4>
  <%= @todo.completed %>
</h4>


<%= link_to 'Back', todos_path %>